# Generated by Django 5.0 on 2024-01-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre del cliente')),
                ('apellido', models.CharField(max_length=250, verbose_name='Apellidos del cliente')),
                ('email', models.EmailField(max_length=250, verbose_name='Correo del Cliente')),
                ('addres', models.CharField(max_length=250, verbose_name='Direccion del Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
