# Generated by Django 5.0 on 2024-01-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
