# Generated by Django 5.0 on 2024-01-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del Cluster')),
                ('addres', models.CharField(max_length=250, verbose_name='Direccion del Cluster')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('Ing', models.FloatField(verbose_name='Longitud')),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
                'ordering': ['name'],
            },
        ),
    ]
