# Generated by Django 5.0 on 2024-01-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='c_cluster',
            field=models.CharField(default=1, max_length=10, verbose_name='Codigo del Cluster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cluster',
            name='fabricante',
            field=models.CharField(choices=[('salvadoreño', 'Salvadoreño'), ('tico', 'Tico'), ('guatemalteco', 'Guatemalteco')], default='salvadoreño', max_length=50, verbose_name='Fabricante'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='tipo',
            field=models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical')], default='horizontal', max_length=20, verbose_name='Tipo'),
        ),
    ]
