# Generated by Django 5.0 on 2024-01-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_cluster_c_cluster_cluster_fabricante_cluster_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='n_bandejas',
            field=models.CharField(choices=[(1, 'numero de bandejas: 1'), (2, 'numero de bandejas: 2'), (3, 'numero de bandejas: 3'), (4, 'numero de bandejas: 4'), (5, 'numero de bandejas: 5'), (6, 'numero de bandejas: 6')], default=1, max_length=50, verbose_name='Numero de Bandejas'),
        ),
    ]
