# Generated by Django 5.0 on 2024-01-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_cluster_n_bandejas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ['id'], 'verbose_name': 'Cluster', 'verbose_name_plural': 'Clusters'},
        ),
    ]
