# Generated by Django 5.0 on 2024-01-19 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_cluster_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la ruta')),
                ('geojson_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bandeja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=250, verbose_name='Nombre del Servicio')),
                ('color', models.CharField(choices=[('Azul', 'Azul'), ('Anaranjado', 'Anaranjado'), ('Verde', 'Verde'), ('Cafe', 'Cafe'), ('Plateado', 'Plateado'), ('Blanco', 'Blanco'), ('Rojo', 'Rojo'), ('Negro', 'Negro'), ('Amarillo', 'Amarillo'), ('Violeta', 'Violeta'), ('Rosa', 'Rosa'), ('Agua', 'Agua')], default='Azul', max_length=20, verbose_name='Color')),
                ('perdida', models.FloatField()),
                ('color_salida', models.CharField(choices=[('Azul', 'Azul'), ('Anaranjado', 'Anaranjado'), ('Verde', 'Verde'), ('Cafe', 'Cafe'), ('Plateado', 'Plateado'), ('Blanco', 'Blanco'), ('Rojo', 'Rojo'), ('Negro', 'Negro'), ('Amarillo', 'Amarillo'), ('Violeta', 'Violeta'), ('Rosa', 'Rosa'), ('Agua', 'Agua')], default='Azul', max_length=20, verbose_name='Color Salida')),
                ('servicio_salida', models.CharField(max_length=250, verbose_name='Nombre del Servicio de Salida')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandejas', to='map.cluster', verbose_name='Cluster')),
            ],
        ),
    ]
