# Generated by Django 5.0 on 2024-02-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_ruta_options_remove_cluster_fabricante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='color',
            field=models.CharField(default='blue', max_length=20),
        ),
    ]
