# Generated by Django 5.0 on 2024-02-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_ruta_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='n_fusiones',
            field=models.IntegerField(choices=[(6, '6 fusiones'), (12, '12 fusiones'), (24, '24 fusiones'), (48, '48 fusiones')], default=1, verbose_name='Numero de Fusiones'),
        ),
    ]
