# Generated by Django 5.0.3 on 2024-04-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0009_cluster_n_fusiones"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="colors",
            field=models.CharField(
                choices=[
                    ("Azul", "Azul"),
                    ("Anaranjado", "Anaranjado"),
                    ("Verde", "Verde"),
                    ("Cafe", "Cafe"),
                    ("Plateado", "Plateado"),
                    ("Blanco", "Blanco"),
                    ("Rojo", "Rojo"),
                    ("Negro", "Negro"),
                    ("Amarillo", "Amarillo"),
                    ("Violeta", "Violeta"),
                    ("Rosa", "Rosa"),
                    ("Agua", "Agua"),
                ],
                default="Azul",
                max_length=20,
                verbose_name="Color de Tubo",
            ),
        ),
    ]
