# Generated by Django 5.0.3 on 2024-04-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0010_cluster_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="tipos",
            field=models.CharField(
                choices=[
                    ("Horizontal", "Horizontal"),
                    ("Vertical", "Vertical"),
                    ("Tipo Domo", "Tipo Domo"),
                ],
                default="Horizontal",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
