# Generated by Django 5.0.2 on 2024-04-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_cluster_tipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='comentario',
            field=models.CharField(default=1, max_length=255, verbose_name='Comentario de la ruta'),
            preserve_default=False,
        ),
    ]
